---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: stg-apps
data:
  ENVIRONMENT: "staging"
  FRONTEND_URL: "https://stg.fullcolombiano.com"
  VERIFY_EMAIL_URL: "https://stg.fullcolombiano.com/verify-email"
  RESET_PASSWORD_URL: "https://stg.fullcolombiano.com/reset-password"
  CORS_ORIGINS: "https://stg.fullcolombiano.com,https://api-stg.fullcolombiano.com"
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_FROM_NAME: "Full Colombiano Staging"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: stg-apps
type: Opaque
stringData:
  # Update these with your actual secrets
  SECRET_KEY: "CHANGE_ME_GENERATE_WITH_openssl_rand_base64_32"
  DATABASE_URL: "postgresql+asyncpg://user:pass@host:5432/dbname"
  DATABASE_URL_SYNC: "postgresql://user:pass@host:5432/dbname"
  MAIL_USERNAME: "your-email@gmail.com"
  MAIL_PASSWORD: "your-app-password"
  MAIL_FROM: "noreply@fullcolombiano.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: stg-apps
  labels:
    app: backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: api
        image: ghcr.io/colombian-suppliers/full-colombiano-backend:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: stg-apps
spec:
  selector:
    app: backend-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-api
  namespace: stg-apps
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api-stg.fullcolombiano.com
    secretName: backend-api-tls
  rules:
  - host: api-stg.fullcolombiano.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-api
            port:
              number: 80

